from time import sleep
print('--- ALUGUE ---')
sleep(2)
km_percorridos = int(input('Quantos kilometros percorreu?\n -->'))
dias_alugado = int(input('Quantos dias alugou o carro?\n -->'))
sleep(1)
print('A calcular custos', end='')
sleep(1)
print('.', end='')
sleep(1)
print('.', end='')
sleep(1)
print('.')
sleep(1)
print('O preço final é', (km_percorridos * 0.456) + (dias_alugado * 60),'€')